### ISSUE TITLE
[Discussion] Should we manually create a server?

### ISSUE THREAD

**Issue by jshin49** [tangoclinh1995/thehonorclub-mobileapp#11]
Maybe we can use AWS or Heroku for hosting our files and managing OAuth and Firebase Database.

Especially regarding OAuth on Ionic, it might be better to have a server unit managing the backend logic.

What do you guys think?

**Comment by linhnta925** [comment]
Yeah it is not very convenient to handle the data logic (which is usually handled in backend) in frontend.

However, I can think of one solution:
- You encapsulate your data-related logic into an **Angular service**
- Then, inject that service into the controller that needs the data
