### ISSUE TITLE
[Discussion] Should we use SASS for styling?

### ISSUE THREAD

**Issue by cameronsuen** [tangoclinh1995/thehonorclub-mobileapp#13]
Ionic comes with the option of using sass css preprocesser for styling.  To achieve cohorent theming (e.g. colors), I think we should use SASS, which has supports features like variables and mixin.

One real use of SASS is in the timepicker and datepicker library, they have predefined colors, but I want to switch to the color specified in the official ionic theme (e.g. assertive, positive).  Instead of hard coding the hex value, I think it's better to use SASS variables defined in ionic.  What do you guys think?

**Comment by linhnta925** [comment]
I didn't think of that when I created this repo, so I removed all SASS (or SCSS) related code in the Gulp file, which is required to compile SASS to CSS. Sorry about that :joy:

If you want to use SASS, can you take a look that the Gulp file in the Ionic repo template (try `ionic startapp <app_name> tabs`) and [here](http://ionicframework.com/docs/cli/sass.html) and issue a Pull request
