### ISSUE TITLE
[Implementation] Sync issues between profilepage-form and profilepage-ctrl

### ISSUE THREAD

**Issue by YoungseogChung** [tangoclinh1995/thehonorclub-mobileapp#20]
Synchronisation issues with profilepage-form and profilepage-controller
-as identified by Linh, coming from Angular properties, logic, and implementation of profilepage-ctrl javascript
-will fix

**Comment by YoungseogChung** [comment]
I just pushed the changes to my branch
Now, I'm thinking about creating a separate page for the skill and position list so that you can do all modifications to the list (add and delete) on separate pages

What do you think, Linh?

**Comment by linhnta925** [comment]
Can you fix this as well:
- Change **userInfo.skills** into **skills** only
- Change **userInfo.desiredPositions** into **desiredPositions** only

By the way, you SHOULD NOT change the content of the **www/index.html** file :joy: This file should be kept unchanged throughout the project.

If you want to create a new page, then create it as a file in the **www/templates** folder. This is how Angular works: When user requests to navigate to the Profile Page, Angular will get the template of the Profile Page (from the file in **www/templates** folder), attach it with the controller and load it into **www/index.html** file

Please refer to [here](https://github.com/tangoclinh1995/sample-ionic-project/tree/master/www/templates) to understand how to write a template.

**Comment by linhnta925** [comment]
**About separating page for skill & position**, I think it is not necessary now.

After you finish this Profile Form, you can move on to creating the Dashboard feature, please talk to @jennykang about this part. If you have questions, feel free to ask me 👌 Open a new issue when you and @jennykang start doing it

**Comment by linhnta925** [comment]
@juked060 You can open a pull request for your code now

**Comment by YoungseogChung** [comment]
@tangoclinh1995 omg, so sorry my bad :(
I made the remaining fixed and moved the file to www/templates.
I also reverted all the content of index.html with the master branch version.
