### ISSUE TITLE
[Implementation] Routing template not rendering

### ISSUE THREAD

**Issue by jshin49** [tangoclinh1995/thehonorclub-mobileapp#21]
Using urlrouter, template HTML should render in <ion-nav-view> tag, but not doing so.

Anyone with similar issues?

**Comment by linhnta925** [comment]
Maybe I spot the problem. This line of code in login.controller.js:

```
angular.module('thehonorclub', [])
```

Should be:

```
angular.module('thehonorclub')
```

**Comment by jshin49** [comment]
What do you think it should be?

Changing to

``` javascript
angular.module('thehonorclub')
```

doesn't work

**Comment by linhnta925** [comment]
It reinitializes the whole module

**Comment by jshin49** [comment]
I don't know what fixed it, but it's suddenly starting to work :)

**Comment by jshin49** [comment]
I figured it out. The js files were cached, so it wouldn't reflect the change immediately for some reason.

The issue you pointed out was correct, and so was the reason.
