### ISSUE TITLE
[Discussion] Our branches seem to be going haywire 

### ISSUE THREAD

**Issue by svm96** [tangoclinh1995/thehonorclub-mobileapp#23]
<img width="1064" alt="screen shot 2016-11-13 at 8 20 41 am" src="https://cloud.githubusercontent.com/assets/19931215/20242910/698924dc-a97a-11e6-97e1-4bf1e3f37d8f.png">
To be honest, I'm not that experienced with merging, rebasing, conflict management and all that, but looking at this, I do wonder if all these branches will be able to successfully get merged back to master(especially branches that branched off at different points from master, if you get what I mean). So what do you guys think? For example, aren't event_management, oauth and redirect_when_notlogin working on three different versions of master?

**Comment by linhnta925** [comment]
It's normal to have different branchs starting from different points of master.
As soon as we don't edit the same file on different branch, the merging will be smooth.

**Comment by svm96** [comment]
<img width="767" alt="screen shot 2016-11-13 at 10 31 20 am" src="https://cloud.githubusercontent.com/assets/19931215/20243294/b1f68766-a98c-11e6-80dd-1ad0591e6f3c.png">
Ah, okay. I wasn't sure after seeing this and that graph. Thanks for clarifying!
