### ISSUE TITLE
[Implementation] Re-implement pushing event to firebase using push()

### ISSUE THREAD

**Issue by cameronsuen** [tangoclinh1995/thehonorclub-mobileapp#24]
As suggested by @tangoclinh1995 in #2, current implementation of creation of new event in firebase is not efficient as the whole event list is monitored and updated real time.  To save computation power, I propose that we use the push() method to do so, i.e.

var newEventRef = firebase.database.ref().child("event").push();

**Comment by linhnta925** [comment]
Hi @sleeplessclassics, please pay attention to this detail when you develop something which relates to the database

**Comment by sleeplessclassics** [comment]
Sure, I will be working on the events which need to be stored in the database. I will use the push method.
