### ISSUE TITLE
[Discussion] Dashboard Page: Ideas and Components 

### ISSUE THREAD

**Issue by YoungseogChung** [tangoclinh1995/thehonorclub-mobileapp#28]
Non-first time users will see the Dashboard page as the landing page once they activate the app.
This page should feature:
     - a list of events that the user is involved in (either as leader of member); 
       a small symbol on the side of each event item to indicate if the user is a team leader in the event
        --> once clicked, expand to show 
              - a list of members in the team (click to access the _profile page_(?))    
     -a button "browse and join events"

**Comment by YoungseogChung** [comment]
We didn't really touch too much on this during our last whole group meeting, so please feel free to add any ideas/suggestions

**Comment by linhnta925** [comment]
For event which user joins as a team leader, perhaps there should be a button call "Recruit more member" or something similar.

This button helps the leader recruits more team member.

What do you think?

**Comment by YoungseogChung** [comment]
Yeah that seems like a great idea

Maybe if we have time, we could have a "Browse other teams" button for the team member user as well.

**Comment by jennykang** [comment]
I was thinking of the possibility of having the dashboard as a side menu? What do you guys think about this?
