### ISSUE TITLE
[Error] Build fails for IOS 

### ISSUE THREAD

**Issue by jennykang** [tangoclinh1995/thehonorclub-mobileapp#29]
Running `ionic build ios` fails with the following error:
```
Running command: hooks/after_prepare/010_add_platform_class.js 

Error: spawn EACCES
```

- [ ] fix

**Comment by linhnta925** [comment]
Does this happen because of Admin/sudo user problem?
On Windows, sometimes I have to run command as administrator in order for it to be proceeded

**Comment by jennykang** [comment]
@tangoclinh1995 this seem to be an issue with `ionic hooks`. Somehow ionic can not find the file although it exists and hence throws `EACCES`. but I will try to run it in admin (`sudo`) to see if it works. 

Thanks for the suggestion @tangoclinh1995 ! :)
