### ISSUE TITLE
[Implementation] Profile Page: Form

### ISSUE THREAD

**Issue by YoungseogChung** [tangoclinh1995/thehonorclub-mobileapp#3]
A page that each user can customize to include information about oneself is needed. 
The page should allow the user to enter a brief description, skills, and fitting positions.

**Comment by linhnta925** [comment]
Please bind the following variables to your HTML elements:
- **name** (User name)
-  **bio** (Short description about the user)
- **photoURL** (User photo URL)
- **skills** (Array of user's skill tags)
- **desiredPositions** (Array of user's desired positions)
- **isSavingProfile** (boolean variable, indicate whether the profile is being save to Firebase. You can bind this variable to the Save button)

And this is a list of function you can bind:
- **_addSkill**__(skill)_
- **_removeSkill**__(skill)_
- **_addPosition**__(position)_
- **_removePosition**__(position)_
- **_saveProfile**__()_
