### ISSUE TITLE
[Improvements] Add more icons

### ISSUE THREAD

**Issue by jennykang** [tangoclinh1995/thehonorclub-mobileapp#30]
The project currently needs more icon sizes to fully support IOS. It should be generated with `ionic resources`

- [ ] fix

**Comment by linhnta925** [comment]
I think Ionic already provides a lot of icon.
Are they enough for our usage at the moment?

http://ionicons.com/

**Comment by jennykang** [comment]
@tangoclinh1995 I added more icon sizes in my branch : https://github.com/tangoclinh1995/thehonorclub-mobileapp/tree/ios-fixes

This fixes the ios build. Will get a PR soon :)
