### ISSUE TITLE
[Enhancement] Customize app theme

### ISSUE THREAD

**Issue by jennykang** [tangoclinh1995/thehonorclub-mobileapp#31]
Ionic comes with default palette of colors. We should customize the color scheme to uniquely match our project. 

Could be possible by modifying: `./scss/ionic.app.scss`

**Comment by linhnta925** [comment]
@hpsuenaa talked to me about this sometimes ago because he also needs to use some SCSS for his part.
He has written a gulp task which combine all SCSS files into a single CSS file.
Perhaps you can talk to me for more details
