### ISSUE TITLE
[Implementation] Dashboard Page: Form

### ISSUE THREAD

**Issue by YoungseogChung** [tangoclinh1995/thehonorclub-mobileapp#34]
Dashboard page listing all events the user is involved in
Clicking each event will take the user to the event page
Browse other event button at the bottom

**Comment by jennykang** [comment]
I think we can also display the user's information as well. Just a brief profile maybe with name and list of skills. And perhaps for each event, there can be a tag about what role or skill tag they used to apply for the event. For example, I might join eventA as a developer and eventB as a designer. So on the list, next to eventA, there could be a tag 'developer' and for eventB a tag as 'designer' or something similar.
