### ISSUE TITLE
[Implementation] Tag standardization (Angular service)

### ISSUE THREAD

**Issue by linhnta925** [tangoclinh1995/thehonorclub-mobileapp#35]
Hi @sleeplessclassics and @hpsuenaa, in case you need to work with skill tags, position tags, please use the Angular service **$tagStandardizeHelper** below to process user input of tags before adding them to Database:

https://github.com/tangoclinh1995/thehonorclub-mobileapp/blob/master/app/js_services/tagStandardizeHelper.service.js

You can use this service by **injecting** it to the controller/services you need to implement and make a function call like this:

***standardize_tag = $tagStandardizeHelper(input_tag)***

**Comment by sleeplessclassics** [comment]
Noted. Thanks a lot for the information
