### ISSUE TITLE
[Enhancement] Share links for the event

### ISSUE THREAD

**Issue by sleeplessclassics** [tangoclinh1995/thehonorclub-mobileapp#38]
When Cameron( @hpsuenaa )  and I first discussed about the events, we visited eventbrite and we came across share links like in the picture attached. What do you guys think about implementing this feature and if we do implement this feature, which all social networks do we make it shareable on?
![1](https://cloud.githubusercontent.com/assets/19663568/20258001/54406db0-aa88-11e6-9347-60f4d6ff0e23.JPG)

**Comment by linhnta925** [comment]
That's a good idea.

But this sharing depends on the web version of our app (I guess this because we need to share an URL on social network, which is not available right now for our mobile app).

So as soon as we start the web version, I think we can add this kind of feature into our mobile app.

**Comment by sleeplessclassics** [comment]
Alright, yeah. I think this would be a good way to move forward.
