### ISSUE TITLE
[Bug] Scrolling doesn't work on Browser

### ISSUE THREAD

**Issue by jshin49** [tangoclinh1995/thehonorclub-mobileapp#56]
On ionic serve, in the browser, scrolling doesn't seem to work (need to find a workaround, or identify the issue).

Is this normal?

**Comment by linhnta925** [comment]
Oh, I experience this problem before.
Try wrapping your HTML with <ion-content>

**Comment by jshin49** [comment]
@tangoclinh1995 wrap with what?

**Comment by linhnta925** [comment]
Sorry, try wrapping with < ion-content >

**Comment by jshin49** [comment]
it already is wrapped with ion-content if you see

**Comment by jshin49** [comment]
Including SCSS bundle back in the gulp file made the swiping work.
