### ISSUE TITLE
Event list

### ISSUE THREAD

**Issue by sleeplessclassics** [tangoclinh1995/thehonorclub-mobileapp#57]
I am designed a card list with infinite scroll for event list. The card looks like the image attached. Icon the left and the event name on the right. 
If you click the icon, it redirects you to event information or else if you click the card, it redirects to team creation/join page. 

So along with the team name should I show anything else in the event card.
Event has start/end date (optional), start/end time(optional), min max size, description, contact email and location. 

I was wondering if we also want to show contact email as well.

**Comment by sleeplessclassics** [comment]
![image](https://cloud.githubusercontent.com/assets/19663568/20299329/742ea772-ab55-11e6-912d-01a60b9c745a.png)

**Comment by linhnta925** [comment]
Yes, I think you can show the email contact of the event.
Basically, you can show any useful information you have already saved in the Firebase Database.

However, I don't understand this part: 
**_So along with the team name should I show anything else in the event card.**_

Why is there team name in the event list?

**Comment by sleeplessclassics** [comment]
Sorry, I meant event name

**Comment by sleeplessclassics** [comment]
I think it is cleared now though
