### ISSUE TITLE
Spaces in Standardized Tags

### ISSUE THREAD

**Issue by svm96** [tangoclinh1995/thehonorclub-mobileapp#59]
Hey @tangoclinh1995 , in your tagStandardizedHelper, there's this line: 
`tag = tag.replace(" . ", " ");`

So, this reduces two spaces to one (But single spaces will still remain unchanged), is that what you were going for?

[There's no dot in there, I put it there because github kept reducing the two spaces to one]

**Comment by linhnta925** [comment]
Yep, this is the purpose of the function. Reduce all sequence of white space which length >= 2 into single space

**Comment by svm96** [comment]
Okay cool
