### ISSUE TITLE
Unit testing directive

### ISSUE THREAD

**Issue by svm96** [tangoclinh1995/thehonorclub-mobileapp#62]
Hi,
I'm writing the unit testing for the card controller, and I don't know how to test this directive code:
`.directive('noScroll', function() {

  return {
    restrict: 'A',
    link: function($scope, $element, $attr) {

      $element.on('touchmove', function(e) {
        e.preventDefault();
      });
    }
  }
})`
I've tried something (take a look at card_testing branch), but it doesn't work. What do you think I should do?

**Comment by linhnta925** [comment]
Take a look at this site:
https://www.sitepoint.com/angular-testing-tips-testing-directives/

I think the information provided is sufficient
